-- Enable pgvector
create extension if not exists vector;

-- Knowledge base chunks
create table if not exists public.documents (
  id bigserial primary key,
  content text not null,
  metadata jsonb default '{}'::jsonb,
  embedding vector(1536)
);

-- Semantic search function used by Supabase/n8n vector retrieval
create or replace function public.match_documents(
  query_embedding vector(1536),
  match_count int default 5,
  filter jsonb default '{}'::jsonb
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language sql
stable
as $$
  select
    documents.id,
    documents.content,
    documents.metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from public.documents
  where documents.metadata @> filter
  order by documents.embedding <=> query_embedding
  limit match_count;
$$;

-- Leads captured from conversations
create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  session_id text not null,
  name text,
  email text,
  company text,
  intent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.leads
  drop constraint if exists leads_session_email_unique;

alter table public.leads
  add constraint leads_session_email_unique unique (session_id, email);

-- Conversation observability
create table if not exists public.conversation_logs (
  id bigint generated by default as identity primary key,
  session_id text not null,
  user_message text not null,
  assistant_reply text not null,
  needs_human boolean not null default false,
  handoff_type text
    check (handoff_type is null or handoff_type in ('user_requested','ai_fallback')),
  created_at timestamptz not null default now()
);

alter table public.conversation_logs
  add column if not exists handoff_type text
  check (handoff_type is null or handoff_type in ('user_requested','ai_fallback'));

-- Human follow-up queue
create table if not exists public.escalations (
  id uuid primary key default gen_random_uuid(),
  session_id text not null,
  user_message text not null,
  reason text,
  handoff_type text not null default 'ai_fallback'
    check (handoff_type in ('user_requested','ai_fallback')),
  summary text,
  assigned_to text,
  status text not null default 'open'
    check (status in ('open','in_progress','resolved')),
  created_at timestamptz not null default now(),
  accepted_at timestamptz,
  resolved_at timestamptz
);

-- Safe upgrade path for repositories that already created the original table.
alter table public.escalations
  add column if not exists handoff_type text not null default 'ai_fallback'
  check (handoff_type in ('user_requested','ai_fallback'));

alter table public.escalations
  add column if not exists summary text;

alter table public.escalations
  add column if not exists assigned_to text;

alter table public.escalations
  add column if not exists accepted_at timestamptz;

create index if not exists idx_conversation_logs_session_id
on public.conversation_logs(session_id);

create index if not exists idx_escalations_status
on public.escalations(status);

create index if not exists idx_escalations_handoff_type
on public.escalations(handoff_type);
